# Generated by Django 4.2.6 on 2023-12-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('pro_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pro_img', models.FileField(upload_to='project_imgs')),
                ('pro_name', models.CharField(max_length=50)),
                ('pro_description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_img', models.FileField(upload_to='user_imgs')),
                ('about', models.TextField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
