# Generated by Django 4.2.6 on 2023-12-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_projectdetails_projectdetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='project_link',
            field=models.URLField(default='/'),
        ),
    ]
