# Generated by Django 4.2.6 on 2023-12-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_certificate_userdetail_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='user_img',
            field=models.FileField(upload_to='user_imgs'),
        ),
    ]
