# Generated by Django 4.2.6 on 2023-12-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_userdetail_user_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certificate',
            new_name='Certificates',
        ),
    ]
