# Generated by Django 4.2.6 on 2023-12-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_certificate_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='Link',
            field=models.URLField(default='/'),
        ),
    ]
