# Generated by Django 4.2.6 on 2023-12-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_certificates_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='crt_description',
            field=models.TextField(default='None', max_length=100),
        ),
    ]
